name: Release
on:
  release:
    types:
      - published

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
      - ubuntu-22.04
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: setup-tools
        uses: buildpacks/github-actions/setup-tools@v5.8.7
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v5.8.7
      - id: package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
          VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
          PACKAGE="${REPO}/$(echo "$BP_ID" | sed 's/\//_/g')"
          pack buildpack package --target "${TARGET}" --publish ${PACKAGE}:${VERSION}
          DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
          echo "::set-output name=bp_id::$BP_ID"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=address::${PACKAGE}@${DIGEST}"
        shell: bash
        env:
          REPO: ghcr.io/${{ github.repository_owner }}/buildpacks
          TARGET: linux/amd64
      - id: register
        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.8.7
        with:
          token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
          id:      ${{ steps.package.outputs.bp_id }}
          version: ${{ steps.package.outputs.version }}
          address: ${{ steps.package.outputs.address }}
